name: Go

on: [push, pull_request]

env:
  LIBSIGNAL_REF: "v0.36.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: signalapp/libsignal
          path: libsignal
          ref: ${{ env.LIBSIGNAL_REF }}


      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Install libolm
        run: sudo apt-get install libolm-dev libolm3

      - name: Build libsignal
        run: |
          cd libsignal
          sudo apt-get install protobuf-compiler
          cargo build -p libsignal-ffi --release --verbose

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21"]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: signalapp/libsignal
          path: libsignal

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libolm
        run: sudo apt-get install libolm-dev libolm3

      - name: Build libsignal
        run: |
          cd libsignal
          sudo apt-get install protobuf-compiler
          cargo build -p libsignal-ffi --release --verbose

      - name: Run libsignalgo tests
        run: |
          export LIBRARY_PATH=libsignal/target/release
          go test -v -json ./pkg/libsignalgo -cover | gotestfmt

      - name: Run bridge tests
        run: |
          export LIBRARY_PATH=libsignal/target/release
          go test -v -json ./... -cover | gotestfmt
