name: Go

on: [push, pull_request]

env:
  LIBSIGNAL_REF: "v0.36.1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true

      - name: Install libolm
        run: sudo apt-get install libolm-dev

      - name: Download libsignal
        run: |
          curl https://mau.dev/tulir/gomuks-build-docker/-/jobs/artifacts/master/raw/libsignal_ffi.a?job=libsignal%20linux%20amd64 -o libsignal_ffi.a

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.21"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libolm
        run: sudo apt-get install libolm-dev

      - name: Download libsignal
        run: |
          curl https://mau.dev/tulir/gomuks-build-docker/-/jobs/artifacts/master/raw/libsignal_ffi.a?job=libsignal%20linux%20amd64 -o libsignal_ffi.a

      - name: Run libsignalgo tests
        # TODO add pipefail here after the tests don't fail
        run: |
          export LIBRARY_PATH=libsignal/target/release
          go test -v -ldflags "-extldflags -lm" -json ./pkg/libsignalgo -cover | gotestfmt

      - name: Run bridge tests
        run: |
          set -euo pipefail
          export LIBRARY_PATH=libsignal/target/release
          go test -v -json ./... -cover | gotestfmt
